// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#planning-the-deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#technical-requirements[Technical requirements] section.
. Use the Region selector in the navigation bar to choose the AWS Region where you want to deploy Amazon EKS.

NOTE: Amazon EKS and Amazon EFS aren’t currently supported in all AWS Regions. For a current list of supported Regions, see the https://docs.aws.amazon.com/general/latest/gr/aws-service-information.html[endpoints and quotas webpage].

[start=4]
. Select the key pair that you created earlier. In the navigation pane of the https://console.aws.amazon.com/ec2/[Amazon EC2 console], choose *Key Pairs*, and then choose your key pair from the list.


// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-name} AMI

This Quick Start requires a subscription to the AMI for {partner-product-name} in AWS Marketplace.

. Sign in to your AWS account.
. {marketplace_listing_url}[Open the page for the {partner-product-name} AMI in AWS Marketplace], and then choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page loads, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace documentation^].

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start

NOTE: The instructions in this section reflect the older version of the AWS CloudFormation console. If you’re using the redesigned console, some of the user interface elements might be different.

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

. Sign in to your AWS account, and choose one of the following options to launch the AWS CloudFormation template. For help with choosing an option, see link:#_deployment_options[deployment options] earlier in this guide.

[cols=",]
|===
|http://qs_launch_link[Deploy {partner-product-name} into a new VPC on AWS^] 
|http://qs_launch_link[Deploy {partner-product-name} into an existing VPC on AWS^]
|===

WARNING: If you’re deploying {partner-product-name} into an existing VPC, make sure that your VPC has two private subnets in different Availability Zones for the workload instances, and that the subnets aren’t shared. This Quick Start doesn’t support https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html[shared subnets^]. These subnets require https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html[NAT gateways^] in their route tables, to allow the instances to download packages and software without exposing them to the internet.

. Choose one of the following options to launch the AWS CloudFormation template into your AWS account. For help choosing an option, see link:#deployment-options[deployment options] earlier in this guide.

[cols=",",]
|===
|https://fwd.aws/6dEQ7[Deploy Amazon EKS into a +
new VPC on AWS] |https://fwd.aws/e37MA[Deploy Amazon EKS into an +
existing VPC on AWS]
|===

*Important:* If you’re deploying Amazon EKS into an existing VPC, make sure that your VPC has three private subnets in different Availability Zones for the workload instances. These subnets require http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat.html[NAT gateways or NAT instances] in their route tables, to allow the instances to download packages and software without exposing them to the internet. You will also need to tag each private subnet with the tag kubernetes.io/role/internal-elb=true and each public subnet with the tag kubernetes.io/role/elb=true if you want to use the Kubernetes integration with Elastic Load Balancing.

Each deployment takes about 25 minutes to complete.

[start=2]
. Check the Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure where Amazon EKS will be built. The template is launched in the US East (Ohio) Region by default.

*Note:* Amazon EKS and Amazon EFS aren’t currently supported in all AWS Regions. For a current list of supported Regions, see the https://docs.aws.amazon.com/general/latest/gr/aws-service-information.html[endpoints and quotas webpage].

[start=3]
. On the *Select Template* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify Details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary.
